spring.application.name=tp
logging.level.root=INFO
logging.level.com.springboot.tp=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG

# Server port
server.port=8081

# JPA config
spring.jpa.open-in-view=false


jwt.secret=MaCleSecreteTresLonguePourHmacSHA256DePlusDe32Caracteres
jwt.expiration=3600000
jwt.header=Authorization
jwt.prefix=Bearer


app.security.admin-password=admin123
app.security.user-password=user123

# Eureka registration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.preferIpAddress=true
spring.application.name=auth-service
