spring.application.name=catalog-service

logging.level.root=INFO
logging.level.com.springboot.catalog=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Eureka registration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.preferIpAddress=true

# Server port
server.port=8082


spring.security.oauth2.resource-server.jwt.jwk-set-uri=http://auth-service:8081/.well-known/jwks.json