server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Auto-route vers les services Eureka
      routes:
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
